### ISSUE TITLE
On the event that a proxy doesn't respond, the code reaches its recursion limit

### ISSUE THREAD

**Issue by ghost** [chaarlottte/Andrew-Bailey-Annoyer#2]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayshinonome/Downloads/Andrew-Bailey-Annoyer/src/__init__.py", line 24, in run
    self.initial_request()
  File "/home/kayshinonome/Downloads/Andrew-Bailey-Annoyer/src/__init__.py", line 120, in initial_request
    resp = self.session.get(self.complaint_url)
  File "/home/kayshinonome/.local/lib/python3.10/site-packages/tls_client/sessions.py", line 403, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/home/kayshinonome/.local/lib/python3.10/site-packages/tls_client/sessions.py", line 318, in execute_request
    cookies = merge_cookies(self.cookies, cookies)
  File "/home/kayshinonome/.local/lib/python3.10/site-packages/tls_client/cookies.py", line 428, in merge_cookies
    cookies = cookiejar_from_dict(cookies)
  File "/home/kayshinonome/.local/lib/python3.10/site-packages/tls_client/cookies.py", line 418, in cookiejar_from_dict
    cookie_jar = RequestsCookieJar()
  File "/usr/lib/python3.10/http/cookiejar.py", line 1268, in __init__
    policy = DefaultCookiePolicy()
RecursionError: maximum recursion depth exceeded
```

**Comment by ghost** [comment]
In `src/__init__.py` I replaced the run function of the AntiTransNarc class with this
```py
    def run(self) -> None:
        are_we_done = False
        while not(are_we_done):
            try:
                self.initial_request()
                self.captcha = self.handle_captcha()
                response = self.submit_form()
                are_we_done = True
            except:
                ()
```
Its working so far
